App\Entities\Role:
    type: entity
    table: roles
    repositoryClass: App\Repositories\RoleRepository

    indexes:
        idx_roles_name:
            columns: [ name ]

    id:
        id:
            type: integer
            generator:
                strategy: auto

    fields:
        name:
            type: string
            length: 255

        createdBy:
            type: string
            length: 36

        updatedBy:
            type: string
            length: 36

        createdAt:
            type: datetime

        updatedAt:
            type: datetime

    manyToMany:
        permissions:
            targetEntity: App\Entities\Permission
            cascade: [ 'persist' ]
            fetch: EXTRA_LAZY
            joinTable:
                name: role_permissions

        grantable:
            targetEntity: App\Entities\Role
            cascade: [ 'persist' ]
            fetch: EXTRA_LAZY
            joinTable:
                name: role_grantable_roles
